@startuml
left to right direction
skinparam {
  linetype ortho
  packageStyle rectangle
  classAttributeIconSize 0
  shadowing false
  dpi 150
  pageMargin 10
  pageWidth 8.27in
  pageHeight 11.69in
  roundCorner 15
  classFontName Helvetica
}

hide empty members

node analyse
node plot

node ROOT
node "JSON configs"

node "plugin libraries"

node "output data files"

analyse --> ROOT
analyse --> "JSON configs"
analyse --> "plugin libraries"
analyse --> "output data files"
plot --> ROOT
plot --> "JSON configs"
plot --> "output data files"
@enduml
