name: plantuml

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**/*.puml'
      - '.github/workflows/plantuml.yml'

permissions:
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        
          persist-credentials: true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: sudo apt-get update
      - run: sudo apt-get install -y graphviz plantuml

      - run: plantuml -o diagrams docs/*.puml

      - name: Commit diagrams (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/diagrams
          if ! git diff --staged --quiet; then
            git commit -m "Update diagrams [skip ci]"
            git push origin HEAD:${{ github.ref }}
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: docs/diagrams
